---
- name: "cloning the git repo"
  git: repo=https://github.com/anandtiwarics/datasploit dest=/opt/datasploit

- name: installing requirements.txt using pip
  pip: requirements=/opt/datasploit/requirements.txt

- name: collect the python server
  shell: python manage.py collectstatic
  args:
    chdir: /opt/datasploit/
    executable: /bin/bash

- name: migrate the python server
  shell: python manage.py makemigrations
  args:
    chdir: /opt/datasploit/
    executable: /bin/bash

- name: setup the python server
  shell: python manage.py migrate
  args:
    chdir: /opt/datasploit/
    executable: /bin/bash

- name: starting the python server
  shell: nohup python manage.py runserver 0.0.0.0:8000 &
  args:
    chdir: /opt/datasploit/
    executable: /bin/bash
